### ISSUE TITLE
Visualization TODOs from 4/10 Meeting

### ISSUE THREAD

**Issue by deastman** [tufts-ml/covid19-forecasting#18]
Gabe
- [x] Add ability in Dash app to switch between scenarios

Diana
- [x] Add ability for html plots to print out different scenarios

@amosca01 
- [x] Add functionality for jumping to specific date ranges

TBD
- [x] Plot actual clinical data as an additional time series

@amosca01 
- [x] Create workflow to pull in actual clinical data from Tufts

**Comment by deastman** [comment]
@michaelchughes 
Gabe has a working solution for the first two checkboxes. I've brought the code into the Dash app, so hopefully we can redeploy that soon. Ab has incorporated a date range slider. The way this works in Plotly out-of-the-box is a little counterintuitive, so I am going to look into a workaround this weekend.

I need to figure out a good way to keep covid19-forecasting and c19-dashboard in sync. I will sync them up myself this weekend, but having some workflow around that would be good.

**Comment by michaelchughes** [comment]
Does c19-dashboard have any calls to code in covid19-forecasting? If so, we should probably avoid that.

Would like to keep this so that the way it works is that covid19-forecasting calls c19-dashboard, but there is not reverse dependency. 

I think best way to keep in sync is just to have me / you run the latest workflows in covid19-forecasting that use the dashboard, and raise issues if there are problems.

**Comment by deastman** [comment]
We do not have any calls to covid19-forecasting, so should be all set.

**Comment by michaelchughes** [comment]
OK this looks good, all these features have been implemented. Thanks!
