### ISSUE TITLE
ADD functionality so terminal state can happen at other stages

### ISSUE THREAD

**Issue by michaelchughes** [tufts-ml/covid19-forecasting#29]
@cuong450 @gvisani can we add this?

Health state is currently either declining or recovering

Would like to expand this to declining, recovering, or terminal.
Basically, this lets us at each stage when we draw the patient's health state to allow for possibility that they die

As soon as terminal state is drawn, patient leaves the model, so no "duration" here.

Please comment below with your proposal:

* [ ] How should parameters JSON file change?
--- Need to somehow specify of terminal state from each declining state... we'll assume if patient is on recovery path that terminal chance is zero. Probably declining in general ward has *very* low chance, declining in ICU off vent has low chance, declining in ICU on vent has some chance

* [ ] How should the PatientTrajectory.py logic change?
* [ ] Anything else needed?

**Comment by cuong450** [comment]
Here is my proposal:

### I think json params needs to newly include:

> "proba_Die_given_Presenting": 0.000001, (I am random guessing probabilities)
> "proba_Die_given_InGeneralWard": 0.0001,
> "proba_Die_given_OffVentInICU": 0.001,
> "probaDie_given_OnVentInICU": 0.21,

I don't think it needs to include things like pmf_duration_Die_InGeneralWard{"0", 1}, I assume we can just implement this 0-timestep death (for all states) in PatientTrajectory.py>simulate_trajectory function 

### In the PatientTrajectory.py

HEALTH_STATE_ID_TO_NAME = {0: 'Declining', 1: 'Recovering', **2:'Die'**} **needs to be added**

within the while loop of simulate_trajectory function:



> health_state_id = prng.rand() < config_dict['proba_Recovering_given_%s' % state] # modified to account for the newly added DIE, 
> health_state_id stays as 1(Recovering),  when already recovering and the above sampling only occurs when health_state_id previously = 0(Declining)

then from conditional cases of health_state_id = 0,1, or 2 we can newly consider the case of DIE

> self.durations.append(duration_of_ZERO)
> ('next')state = TERMINAL

Overall, I think  PatientTrajectory.py simulating_trajectory is adding 1 new conditional case [health_state_id =  2], rather than modifying much of the previous conditional cases.

**Comment by michaelchughes** [comment]
what if, at the *end* of any state where health state was declining, we just flip the coin then?

That is, in the middle of PatientTrajectory.py

```
            self.state_ids.append(state_name_to_id[state])
            self.health_state_ids.append(health_state_id)
            self.durations.append(duration)
            
            state = next_state_map[state+HEALTH_STATE_ID_TO_NAME[health_state_id]]
             if health_state_id < 1:
                # flip coin to see if death happens
                if prng.rand() < proba_Die_given_STATE:
                     state = 'TERMINAL'
            self.is_terminal_0 = (state == 'TERMINAL' and health_state_id < 1)
```

**Comment by michaelchughes** [comment]
I think that might be simpler than requiring 3 possible health states, etc.

Your JSON proposal is otherwise v good.

**Comment by gvisani** [comment]
I agree with Mike's simpler proposal.

I think we can safely assume that no patient will die from the general ward and from the presenting state, that way we have less complexity to our model. Also, there is no need to model the probability of dying from the ventilator since the terminal state is the only possibility when declining while on the vent (probaDie_given_declining_OnVentInICU = 1.0).
Thus, I think we can simply add the parameter "proba_Die_given_declining_OffVentInICU", which, as Mike suggested, comes in after a patient has been declining.

**Comment by michaelchughes** [comment]
Marking this issue resolved. We've accepted the PR #31 and #32.
